name: Pull Request Code Check

on:
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-setup

      - name: Run checks
        run: npm run check

      - name: Check if buildable
        run: npm run build --production
